# Generated by Django 6.0.6 on 2026-06-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categroy_name',
            new_name='category_name',
        ),
    ]
